### ISSUE TITLE
fails to build on debian sid 20171208

### ISSUE THREAD

**Issue by bsmith94** [linux-rdma/qperf#8]
qperf failed to build on today's update of debian sid.

```
In file included from rdma.c:43:0:
/usr/include/rdma/rdma_cma.h:91:2: error: unknown type name ‘__be16’
  __be16  pkey;
  ^~~~~~
/usr/include/rdma/rdma_cma.h:588:1: error: unknown type name ‘__be16’; did you mean ‘htobe16’?
 __be16 rdma_get_src_port(struct rdma_cm_id *id);
 ^~~~~~
 htobe16
/usr/include/rdma/rdma_cma.h:589:1: error: unknown type name ‘__be16’; did you mean ‘htobe16’?
 __be16 rdma_get_dst_port(struct rdma_cm_id *id);
 ^~~~~~
 htobe16
Makefile:386: recipe for target 'rdma.o' failed
```

**Comment by bsmith94** [comment]
This was due to an outdated local build of rdma-core. Sorry.

**Comment by shangdehao1** [comment]
hi, @bsmith94 do you know how to solve this problem?

**Comment by bsmith94** [comment]
Hi, @shangdehao1 
I closed this issue because it resulted from a transient version of rdma-core. If you're experiencing a build failure, you should probably create a new issue.
Incidentially, qperf builds fine against my sid host, updated this morning.
